name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.MIIJ4gIBAzCCCYwGCSqGSIb3DQEHAaCCCX0Eggl5MIIJdTCCBawGCSqGSIb3DQEHAaCCBZ0EggWZMIIFlTCCBZEGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFDWK1prGeEYGrlibvdwAk+CqFi7nAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQNy9VJ+4LWcRATq3VZFsV5ASCBNDvM+uP7eRmxu2Fkd5lJSVjqosf4TJXrK7QmDsIGIuaSQg4EaR48sN8RQ+/K68thPy9vqGARxkvWgMiZcmJ87hktoxwVfIySrGiLW+ryGC3o0t59Ks3KXCXMz4eCYB3mShiDVAOyB4l7MGUGlQ9P9I1PC9Dn7E4D+T3aK6/aiZDA2P8gmLlTYcF217dYcNBoMZZBy/1shPd9QUDEqbD04CfLVUedjhFzm39hb2EgbarHRFOkfxLrCjLJaWHEOpZSj1y411vk1pKQHiEKSXWgBXQds2sAH7EUHh8cSlCBu4/DT/uBEg1c0gtIDfBYRod+ozgatuA8A8ZVD6K2ch9CyY60ESr2aaTfrRUVbFPHE0h5pX3LR4wsQkgKwFmn4Gx4N7hx6gnVqff1LjNpInzwMGVfb/uEa3ijq6V+MOAnWljWfsRv67RKKZDmW+ouSO7SrNgRbwFr+eNj3SFi8eKSgDFo1sDmuPUrP/DKUZqPc2tgaEtcoH6qvwapFQNEjtibIblrwH9xNP0tmathxivS+Zbhr1GX6yf00sMhXfCaqPq5uNokhk7Nyu80KWiwld3kM0YBZ2atTtl6BpSrMWjZPW/INEltmMlVSB0AR1gefxTIQxyrqvn2F8L8jeWRVqHuxo48MW+k3YFnUGOFBIeU3rjpchFbRm64LmiUyMk9VaJYGX6UGqvYOI3BGRXTlclOFMMhFDytjoAdUYcP8cQLmrquYcuGhef4lyUHZGkJHdM8A+6ioPetr5xim+2M/pTZ5JEib7qtcvcPpbMguR2r0giW4SNclCo6y/A3LbbrEcUw8bL853KDySwJGwc32VtzXXc8BQ7UccT6nmHyKL2sugrtb/2qauOfvzqJadAK6GEuX410FzR6sX4Gj3BlAtgx/ROrdo9o+wzfMBl8t2y5mvs3RGKExVoBbJcGObPLWiXdXWicDk5ageRLLVJJptj6NaSi3RkGz+hDLLsSdjHM/DBM5L0Kc4sz1r3rqb0cmi7Vfms8wW3dtkiHW11MBjhpgPteX/GlVtfKUCGk0lR9aOLz92ph7U0ehoSJHP5E+fLo3IXQfrE7iCB68fhjmgx/lup02b9DpwJ4EGxjWjI2LZ0m29afvWvW7kyDW2ClXe8A8Kp5zCgdvrCucf2qowKBcLab7ThdQF6QIGYlLJRLzl7V0fjKkHQ36F1fI/RDF842dVH0sqN+ZzDdqVER7cWIWU53Ft5kfKr2rX8cxo8PxGVrgRN4ohAZesDRa8q9cfeIdFhg9jTZwZCcDnWk3s70aO2rDCDq4K0sPRUK3UINki1n8cY3OBwnyok0L8Mnw2BPi7XKI87t4Pot6ZLoAuJRYm/Jr9VaN5vZKyd6w7UCHpIPv/81j+XVlooz88Qr9Xrytb/c+4G6OEDyKu4z2RyM73EX19gduurBzrn3/XjmDAwixX9ZDq6JiYFR5nEOOQ1+Sc05d2lszcp8T/vph50ri1gqgOab2rRtsKrAha2NL5VFkqClJ0iwnUBNOMggReGmz4T0Pli2pRNdb1FHrmdBus8Q31dd/yUjSEPR2VPvf5hsVn33gq+MRPXhyZEVsw8PRMwm1UOMs5tWiF7ytC/2O+FJ4IWtzWZxgVCSgpYQHn3lAHtHxYDAPsQ11LbWswOhDE+MBkGCSqGSIb3DQEJFDEMHgoAawByAG8AbgBvMCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE3NzY3OTczMjM2MzMwggPBBgkqhkiG9w0BBwagggOyMIIDrgIBADCCA6cGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUTUIbIcGzwwEtCB6mTPD5O6PjCZACAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBBbcZ4OzmHoy+RIPNFrU40ngIIDMBlwAyQJa2LfvdXXtuBhEI2tjNjBTih+K2PNylg9/yxkAqHVK8ACsjLomk85tpH0UKm0NPKcPAJUVg4AgWH1AxhdqwQKU4cmkO8RuB0MhhI4cLDhaRmyKGvXs1t7ObQsA0Wd8v88Aue0xeaBrWJYUf71erH9osb47YPXwUqfzifRrrkd86TUJ15I8590rRbXd0sgb/9Y7RaY+SluoZYrVXLHuCzavesIh6vjRQilPJfzeIGikSiqxmBVcSRshQtQZaaniLAUI4atDOO7DrRS8T8tE+RemoBu1lKy7mxAzHp0uxKFmJ5h4uBfr0A29Anu85WfJZtAo3aKZU88DSV5G33EpgmWQRvNku8QbBqSI7P93mA8WaC/3ujNGLm/dru/27iEcCcIjZZPPrFckgLfzNpnnhMHoN+AgjZU5TWVbLWEn+zhzI8WwcyuzN7LVOfGg8S92oD1PGVnkFaMPUgE0OATVCbl9HL2OsNDx6BOimJPzgGdpoytyB069aPvZOC36mcUkHXAtJrq6PL4nt+r3Kr6yhDyIGgJExWJ9SAoKVx1g9V79ZTXhf6ANce+YG+R91at/b8I/r4t4CjhScC7nuPp552C7m0c/fc89hsNn2TCtsvTDjHDgmCZmxqKdzR5QrB/3MDdmJz2OdgJPTtYVkBJhBWQ5PmLuN5yj4dGOTgUhKZrA7NuXefhbeDtykLPaFm0c32mPETEdZ59vP7+/perYBaJDqkZQ1IuvynDqIkz1T42+cHrOLldu1HWw14vFGmeU4EqYHpWD9oVGaXgYrt4E/JkWnnVu8fdTJXl6OZKd9j+oJnJuN2AnzqvzN5pRGjorZm+E79ed45WqeJgx095gv18VpF0iZMZiN0nh4ojpJn7odk2+YTXkc1oBb/OvnqcRmjjZU7YxTIIVW28M3/3sLtvL1Sj0bma5xBIGjcFvpFsX4tueoZz5Axa4vIgYgeQqDw115aEk7QodUCubDQb/Qx1L4cFGpabVRIM5jKwNCBav4b+RKeWjnbgT08PbrZ62/FwlLBVt1x6IeWDYJ8bdkMQjSK3oMgYY5ewlUqVYp9SgHfDinJ+E+xqN8zSHTBNMDEwDQYJYIZIAWUDBAIBBQAEIM+Ou+LraRjd9k6ttXADFkDaTXe7Vo/A6RvmogUVXe8ABBT5Q9D5dz33NXbnlkZIbAuZj5QKRQICJxA= }}" | base64 --decode > app/krono-key.jks

      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: E:\KRONO\chaves\krono-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.krono1020 }}
          KEY_ALIAS: ${{ secrets.krono }}
          KEY_PASSWORD: ${{ secrets.krono1020 }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
